services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-nota-fiscal
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      PORT: 3333
    ports:
      - "127.0.0.1:3333:3333"
    volumes:
      - ./schemas:/app/schemas:ro
    networks:
      - default
      - n8n_proxy
    command: sh -c "npm run prisma:migrate:deploy && npm start"
    mem_limit: 512m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  n8n_proxy:
    external: true
    name: n8n_default
